
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_androhid_NativeBtHid */

#ifndef _Included_org_androhid_NativeBtHid
#define _Included_org_androhid_NativeBtHid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_pmxota_OtaLoadJNI
 * Method:    setupClient
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_pmxota_OtaLoadJNI_setupClientSocket(JNIEnv *, jobject);

/*
 * Class:     com_example_pmxota_OtaLoadJNI
 * Method:    connectToHost
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_pmxota_OtaLoadJNI_connectToHost(JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_pmxota_OtaLoadJNI
 * Method:    deconnectClient
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_pmxota_OtaLoadJNI_deconnectClient(JNIEnv *, jobject);

/*
 * Class:     com_example_pmxota_OtaLoadJNI
 * Method:    startOTAUpdate
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_pmxota_OtaLoadJNI_startOTAUpdate(JNIEnv *env, jobject obj, jstring fwFilePath, jstring isVerboseLogS);

/*
 * Class:     com_example_pmxota_OtaLoadJNI
 * Method:    isEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_pmxota_OtaLoadJNI_isEnabled(JNIEnv *, jobject);

/*
 * Class:     com_example_pmxota_OtaLoadJNI
 * Method:    btDeviceScan
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_pmxota_OtaLoadJNI_btDeviceScan(JNIEnv *, jobject);

/*
 * Class:     com_example_pmxota_OtaLoadJNI
 * Method:    btDeviceGetName
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_pmxota_OtaLoadJNI_btDeviceGetName(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
